### ISSUE TITLE
ffmpeg EACCES error

### ISSUE THREAD

**Issue by muxa** [homebridge-plugins/homebridge-camera-ffmpeg#561]
**Describe The Bug:**
Snapshot or video stream fails.

**To Reproduce:**
Every time I open the camera in Home app

**Expected behavior:**
Snapshots should show in the app and video stream in the app when opening the camera.

**Logs:**

```
[6/24/2020, 9:08:27 PM] [Security Cameras] Snapshot from Driveway at 480:270
[6/24/2020, 9:08:27 PM] [Security Cameras] An error occurred while making snapshot request
[6/24/2020, 9:08:35 PM] [Security Cameras] [FFMPEG] Failed to start stream: spawn /homebridge/node_modules/homebridge-camera-ffmpeg/node_modules/ffmpeg-for-homebridge/ffmpeg EACCES
```

**Homebridge Config:**

```json
{
    "bridge": {
        "name": "Homebridge 9347",
        "username": "0E:BC:CB:CA:93:48",
        "port": 53253,
        "pin": "031-45-154"
    },
    "platforms": [
        {
            "name": "Security Cameras",
            "cameras": [
                {
                    "name": "Driveway",
                    "manufacturer": "Reolink",
                    "model": "RLC-410-5MP",
                    "firmwareRevision": "v2.0.0.448_19061407",
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -re -i rtsp://motion:motioneye@192.168.1.59:554/h264Preview_01_sub",
                        "stillImageSource": "-i http://192.168.1.59/cgi-bin/api.cgi?cmd=Snap&channel=0&rs=&user=motion&password=motioneye",
                        "maxStreams": 2,
                        "maxFPS": 15,
                        "maxBitrate": 300,
                        "vcodec": "copy",
                        "videoFilter": "none",
                        "audio": false,
                        "debug": false
                    }
                }
            ],
            "platform": "Camera-ffmpeg"
        }
    ],
    "accessories": []
}
```

**Screenshots:**
n/a

**Environment:**

* **Node.js Version**: v12.18.1
* **NPM Version**: v6.14.5
* **Homebridge Version**: 1.1.1
* **Homebridge Camera FFmpeg Version**: 2.0.0
* **Homebridge Config UI X Plugin Version**: 4.23.0
* **Operating System**: Docker on Raspberry Pi 4

**Comment by donavanbecker** [comment]
Closing this per #554.

**Comment by muxa** [comment]
I have upgrade to latest v2.1.1 of the plugin and this issue still exists:

```
[7/10/2020, 7:10:12 AM] [Security Cameras] Snapshot from Driveway at 480:270
[7/10/2020, 7:10:12 AM] [Security Cameras] ffmpeg -i http://192.168.1.59/cgi-bin/api.cgi?cmd=Snap&channel=0&rs=&user=motion&password=motioneye -frames:v 1 -f image2 -
[7/10/2020, 7:10:12 AM] [Security Cameras] An error occurred while making snapshot request
[7/10/2020, 7:10:12 AM] [Security Cameras] Error: spawn /homebridge/node_modules/homebridge-camera-ffmpeg/node_modules/ffmpeg-for-homebridge/ffmpeg EACCES
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'EACCES',
  code: 'EACCES',
  syscall: 'spawn /homebridge/node_modules/homebridge-camera-ffmpeg/node_modules/ffmpeg-for-homebridge/ffmpeg',
  path: '/homebridge/node_modules/homebridge-camera-ffmpeg/node_modules/ffmpeg-for-homebridge/ffmpeg',
  spawnargs: [
    '-i',
    'http://192.168.1.59/cgi-bin/api.cgi?cmd=Snap&channel=0&rs=&user=motion&password=motioneye',
    '-frames:v',
    '1',
    '-f',
    'image2',
    '-'
  ]
}
```

**Comment by muxa** [comment]
It turned out to be a disk permission issue (the mounted disk had `noexec` flag). I removed it following this: https://forums.plex.tv/t/pms-cannot-transcode-any-file-conversion-failed-the-transcoder-crashed-or-failed-to-start-up/227898/9

**Comment by Sunoo** [comment]
Glad you were able to solve it.
