### ISSUE TITLE
GET Error (Service with the same UUID)

### ISSUE THREAD

**Issue by monza258** [homebridge-plugins/homebridge-camera-ffmpeg#617]
Hi Guys. 

Today I get some errors in Homebridge. Does anyone know what's wrong?

```
Jul 07 21:31:10 raspberrypi homebridge[2016]: [7/7/2020, 21:31:10] [Cameras] Initializing Camera-ffmpeg platform...
Jul 07 21:31:10 raspberrypi homebridge[2016]: [7/7/2020, 21:31:10] [Cameras] Configuring accessory Haustür
Jul 07 21:31:10 raspberrypi homebridge[2016]: [7/7/2020, 21:31:10] Error: Cannot add a Service with the same UUID '00000089-0000-1000-8000-0026BB765291' as another Service in this Accessory without also defining a unique 'subtype' property.
Jul 07 21:31:10 raspberrypi homebridge[2016]:     at Accessory._this.addService (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:276:17)
Jul 07 21:31:10 raspberrypi homebridge[2016]:     at PlatformAccessory.addService (/usr/local/lib/node_modules/homebridge/src/platformAccessory.ts:92:41)
Jul 07 21:31:10 raspberrypi homebridge[2016]:     at FfmpegPlatform.configureAccessory (/usr/local/lib/node_modules/homebridge-camera-ffmpeg/src/index.ts:127:12)
Jul 07 21:31:10 raspberrypi homebridge[2016]:     at /usr/local/lib/node_modules/homebridge/src/server.ts:307:25
Jul 07 21:31:10 raspberrypi homebridge[2016]:     at Array.filter (<anonymous>)
Jul 07 21:31:10 raspberrypi homebridge[2016]:     at Server.restoreCachedPlatformAccessories (/usr/local/lib/node_modules/homebridge/src/server.ts:270:69)
Jul 07 21:31:10 raspberrypi homebridge[2016]:     at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:158:10)
Jul 07 21:31:10 raspberrypi homebridge[2016]:     at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:80:10)
Jul 07 21:31:10 raspberrypi homebridge[2016]:     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
Jul 07 21:31:10 raspberrypi homebridge[2016]:     at Module._compile (internal/modules/cjs/loader.js:1138:30)
Jul 07 21:31:10 raspberrypi homebridge[2016]: [7/7/2020, 21:31:10] Got SIGTERM, shutting down Homebridge...
Jul 07 21:31:11 raspberrypi homebridge[2016]: HAP Warning: Characteristic 00000093-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 0000008D-0000-1000-8000-0026BB765291. Adding anyway.
Jul 07 21:31:11 raspberrypi homebridge[2016]: HAP Warning: Characteristic 00000093-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 0000008D-0000-1000-8000-0026BB765291. Adding anyway.
```

**Comment by donavanbecker** [comment]
you will need to fill out the issue template
